name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - uses: actions/checkout@v4

    # Set up JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 31
        build-tools-version: '31.0.0'
        cmake-version: '3.10.2'

    # Accept Android SDK licenses
    - name: Accept licenses
      run: |
        yes | sdkmanager --licenses

    # Install Emulator System Image
    - name: Install Emulator Image
      run: sdkmanager "system-images;android-31;default;x86_64"

    # Create AVD (Android Virtual Device)
    - name: Create AVD
      run: avdmanager create avd -n test -k "system-images;android-31;default;x86_64" --device "pixel"

    # Start the emulator
    - name: Start Emulator
      run: |
        nohup emulator -avd test -no-window -no-audio -no-boot-anim -accel off &
        adb wait-for-device
        adb shell input keyevent 82 # Unlock screen

    # Wait for the emulator to boot up
    - name: Wait for Emulator to Boot
      run: |
        sleep 60 # Adjust if the emulator takes longer to start
        adb shell getprop init.svc.bootanim | grep -m 1 stopped

    # Grant execute permission for the Gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Run your unit tests or instrumentation tests
    - name: Run Tests
      run: ./gradlew connectedAndroidTest

    # Build the project with Gradle
    - name: Build with Gradle
      run: ./gradlew build
