name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 'latest'
        packages: |
          cmdline-tools;latest
          
    - name: Accept SDK licenses
      run: yes | sdkmanager --licenses || true

    - name: List Available SDK Packages
      run: sdkmanager --list

    - name: Install Required Packages
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "system-images;android-34;default;x86_64" "emulator"

    - name: Set environment variables
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

    - name: Create AVD
      run: avdmanager create avd -n test -k "system-images;android-34;default;x86_64" --device "pixel" --force

    - name: Start Emulator
      run: |
        # Start the emulator in the background
        emulator -avd test -no-window -no-audio -no-boot-anim -accel off &

        # Wait for the device to be ready
        adb wait-for-device

        # Wait until the emulator has fully booted (Increase timeout if needed)
        timeout=600 # 10 minutes timeout
        start_time=$(date +%s)
        while true; do
          if adb shell getprop sys.boot_completed | grep -m 1 '1'; then
            break
          fi
          current_time=$(date +%s)
          elapsed_time=$(( current_time - start_time ))
          if [ $elapsed_time -ge $timeout ]; then
            echo "Emulator failed to boot within the expected time."
            exit 1
          fi
          sleep 1
        done

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Tests
      run: ./gradlew connectedAndroidTest

    - name: Build with Gradle
      run: ./gradlew build
